default: adventure buildrooms
adventure:
	gcc howertor.adventure.c -o howertor.adventure -lpthread
buildrooms:
	gcc howertor.buildrooms.c -o howertor.buildrooms
clean:
	rm -f howertor.adventure howertor.buildrooms
