var testVariable;
testVariable = 5;
document.getElementById("result1").textContent = testVariable;
testVariable = "Here is a string";
document.getElementById("result2").textContent = testVariable;
testVariable = "Both a string...";
document.getElementById("result3").textContent = testVariable;
testVariable = 12.34567890;
document.getElementById("result4").textContent = testVariable;
testVariable = "...and a float";
document.getElementById("result5").textContent = testVariable;
